### ISSUE TITLE
AttributeError: 'TS3Connection' object has no attribute 'keepalive'

### ISSUE THREAD

**Issue by h1rule** [metalfiiish/ts-gw2-verifyBot#6]
How to fix that? pip3 install keepalive not existing?

 python3 TS3Bot.py
Initializing script....
Connecting to Teamspeak server...
Traceback (most recent call last):
  File "TS3Bot.py", line 359, in <module>
    ts3conn.keepalive(interval=250)
AttributeError: 'TS3Connection' object has no attribute 'keepalive'

**Comment by h1rule** [comment]
NVM, i installed the correct TS3 version and now it works.

**Comment by metalfiiish** [comment]
Glad you figured it out! That's a common issue people run into with the ts3 package versions. Thanks for replying with latest status.
